<?php

class m160623_013827_create_role_data_entry extends CDbMigration
{

    public function safeUp()
    {
        $sql = "INSERT IGNORE INTO `AuthItem` (name, type, description) VALUES (:nama, :tipe, :deskripsi)";

        $params = [
            [':nama' => 'barang.assigndefaultsup', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'barang.hapus', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'barang.index', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'barang.listbukansupplier', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'barang.removesupplier', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'barang.tambah', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'barang.tambahsupplier', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'barang.ubah', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'barang.updatehargajual', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'barang.updaterrp', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'barang.view', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'hutangpiutang.hapus', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'hutangpiutang.index', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'hutangpiutang.tambah', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'hutangpiutang.ubah', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'hutangpiutang.view', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'kategoribarang.hapus', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'kategoribarang.index', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'kategoribarang.tambah', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'kategoribarang.ubah', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'kategoribarang.view', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'pembelian.ambilprofil', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'pembelian.getbarang', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'pembelian.hapus', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'pembelian.hapusdetail', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'pembelian.import', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'pembelian.index', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'pembelian.simpanpembelian', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'pembelian.tambah', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'pembelian.tambahbarang', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'pembelian.tambahbarangbaru', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'pembelian.total', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'pembelian.ubah', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'pembelian.updateqty', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'pembelian.view', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'penjualan.ambilprofil', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'penjualan.exportcsv', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'penjualan.hapus', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'penjualan.hapusdetail', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'penjualan.import', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'penjualan.index', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'penjualan.printinvoice', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'penjualan.printnota', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'penjualan.printstruk', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'penjualan.simpanpenjualan', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'penjualan.tambah', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'penjualan.tambahdetail', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'penjualan.total', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'penjualan.ubah', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'penjualan.view', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'profil.hapus', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'profil.index', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'profil.tambah', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'profil.ubah', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'profil.view', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'rakbarang.hapus', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'rakbarang.index', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'rakbarang.tambah', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'rakbarang.ubah', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'rakbarang.view', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'returpembelian.ambilprofil', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'returpembelian.caribarang', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'returpembelian.getbaranginfo', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'returpembelian.hapus', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'returpembelian.hapusdetail', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'returpembelian.index', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'returpembelian.pilihinv', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'returpembelian.printreturpembelian', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'returpembelian.simpan', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'returpembelian.tambah', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'returpembelian.total', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'returpembelian.ubah', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'returpembelian.updateqty', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'returpembelian.view', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'returpenjualan.ambilprofil', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'returpenjualan.hapus', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'returpenjualan.hapusdetail', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'returpenjualan.index', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'returpenjualan.simpan', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'returpenjualan.tambah', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'returpenjualan.tambahdetail', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'returpenjualan.total', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'returpenjualan.ubah', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'returpenjualan.view', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'satuanbarang.hapus', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'satuanbarang.index', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'satuanbarang.tambah', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'satuanbarang.ubah', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'satuanbarang.view', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'stockopname.gantirak', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'stockopname.hapus', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'stockopname.hapusdetail', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'stockopname.index', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'stockopname.inputqtymanual', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'stockopname.scanbarcode', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'stockopname.setinaktif', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'stockopname.setnol', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'stockopname.simpanso', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'stockopname.tambah', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'stockopname.tambahdetail', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'stockopname.ubah', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'stockopname.view', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'tools/cekharga.cekbarcode', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'tools/cekharga.index', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'tools/cetakformso.getkategoriopt', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'tools/cetakformso.index', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'tools/cetakformso.pilihrak', ':tipe' => 0, ':deskripsi' => ''],
            [':nama' => 'cekHarga', ':tipe' => 1, ':deskripsi' => 'Cek Harga Barang'],
            [':nama' => 'cetakFormSO', ':tipe' => 1, ':deskripsi' => 'Form Untuk SO Manual'],
            [':nama' => 'configBarang', ':tipe' => 1, ':deskripsi' => 'Konfigurasi Barang'],
            [':nama' => 'configKategoriBarang', ':tipe' => 1, ':deskripsi' => 'Konfigurasi Kategori Barang'],
            [':nama' => 'configProfil', ':tipe' => 1, ':deskripsi' => 'Konfigurasi Profil'],
            [':nama' => 'configRakBarang', ':tipe' => 1, ':deskripsi' => 'Konfigurasi Rak Barang'],
            [':nama' => 'configSatuanBarang', ':tipe' => 1, ':deskripsi' => 'Konfigurasi Satuan Barang'],
            [':nama' => 'transaksiHutangPiutang', ':tipe' => 1, ':deskripsi' => 'Transaksi Hutang Piutang (Background Process)'],
            [':nama' => 'transaksiPembelian', ':tipe' => 1, ':deskripsi' => 'Transaksi Pembelian'],
            [':nama' => 'transaksiPenjualan', ':tipe' => 1, ':deskripsi' => 'Transaksi Penjualan'],
            [':nama' => 'transaksiReturPembelian', ':tipe' => 1, ':deskripsi' => 'Transaksi Retur Pembelian'],
            [':nama' => 'transaksiReturPenjualan', ':tipe' => 1, ':deskripsi' => 'Transaksi Retur Penjualan'],
            [':nama' => 'transaksiSO', ':tipe' => 1, ':deskripsi' => 'Transaksi Stock Opname'],
            [':nama' => 'DATA_ENTRY', ':tipe' => 2, ':deskripsi' => 'Entry Data Transaksi Inventory, Konfigurasi Data Inventory'],
        ];
        foreach ($params as $param) {
            $this->execute($sql, $param);
        }

        $sql = "INSERT IGNORE INTO `AuthItemChild` (parent, child) VALUES (:parent, :child)";
        $params = [
            [':parent' => 'cekHarga', ':child' => 'tools/cekharga.cekbarcode'],
            [':parent' => 'cekHarga', ':child' => 'tools/cekharga.index'],
            [':parent' => 'cetakFormSO', ':child' => 'tools/cetakformso.getkategoriopt'],
            [':parent' => 'cetakFormSO', ':child' => 'tools/cetakformso.index'],
            [':parent' => 'cetakFormSO', ':child' => 'tools/cetakformso.pilihrak'],
            [':parent' => 'configBarang', ':child' => 'barang.assigndefaultsup'],
            [':parent' => 'configBarang', ':child' => 'barang.hapus'],
            [':parent' => 'configBarang', ':child' => 'barang.index'],
            [':parent' => 'configBarang', ':child' => 'barang.listbukansupplier'],
            [':parent' => 'configBarang', ':child' => 'barang.removesupplier'],
            [':parent' => 'configBarang', ':child' => 'barang.tambah'],
            [':parent' => 'configBarang', ':child' => 'barang.tambahsupplier'],
            [':parent' => 'configBarang', ':child' => 'barang.ubah'],
            [':parent' => 'configBarang', ':child' => 'barang.updatehargajual'],
            [':parent' => 'configBarang', ':child' => 'barang.updaterrp'],
            [':parent' => 'configBarang', ':child' => 'barang.view'],
            [':parent' => 'configKategoriBarang', ':child' => 'kategoribarang.hapus'],
            [':parent' => 'configKategoriBarang', ':child' => 'kategoribarang.index'],
            [':parent' => 'configKategoriBarang', ':child' => 'kategoribarang.tambah'],
            [':parent' => 'configKategoriBarang', ':child' => 'kategoribarang.ubah'],
            [':parent' => 'configKategoriBarang', ':child' => 'kategoribarang.view'],
            [':parent' => 'configProfil', ':child' => 'profil.hapus'],
            [':parent' => 'configProfil', ':child' => 'profil.index'],
            [':parent' => 'configProfil', ':child' => 'profil.tambah'],
            [':parent' => 'configProfil', ':child' => 'profil.ubah'],
            [':parent' => 'configProfil', ':child' => 'profil.view'],
            [':parent' => 'configRakBarang', ':child' => 'rakbarang.hapus'],
            [':parent' => 'configRakBarang', ':child' => 'rakbarang.index'],
            [':parent' => 'configRakBarang', ':child' => 'rakbarang.tambah'],
            [':parent' => 'configRakBarang', ':child' => 'rakbarang.ubah'],
            [':parent' => 'configRakBarang', ':child' => 'rakbarang.view'],
            [':parent' => 'configSatuanBarang', ':child' => 'satuanbarang.hapus'],
            [':parent' => 'configSatuanBarang', ':child' => 'satuanbarang.index'],
            [':parent' => 'configSatuanBarang', ':child' => 'satuanbarang.tambah'],
            [':parent' => 'configSatuanBarang', ':child' => 'satuanbarang.ubah'],
            [':parent' => 'configSatuanBarang', ':child' => 'satuanbarang.view'],
            [':parent' => 'transaksiHutangPiutang', ':child' => 'hutangpiutang.hapus'],
            [':parent' => 'transaksiHutangPiutang', ':child' => 'hutangpiutang.index'],
            [':parent' => 'transaksiHutangPiutang', ':child' => 'hutangpiutang.tambah'],
            [':parent' => 'transaksiHutangPiutang', ':child' => 'hutangpiutang.ubah'],
            [':parent' => 'transaksiHutangPiutang', ':child' => 'hutangpiutang.view'],
            [':parent' => 'transaksiPembelian', ':child' => 'pembelian.ambilprofil'],
            [':parent' => 'transaksiPembelian', ':child' => 'pembelian.getbarang'],
            [':parent' => 'transaksiPembelian', ':child' => 'pembelian.hapus'],
            [':parent' => 'transaksiPembelian', ':child' => 'pembelian.hapusdetail'],
            [':parent' => 'transaksiPembelian', ':child' => 'pembelian.import'],
            [':parent' => 'transaksiPembelian', ':child' => 'pembelian.index'],
            [':parent' => 'transaksiPembelian', ':child' => 'pembelian.simpanpembelian'],
            [':parent' => 'transaksiPembelian', ':child' => 'pembelian.tambah'],
            [':parent' => 'transaksiPembelian', ':child' => 'pembelian.tambahbarang'],
            [':parent' => 'transaksiPembelian', ':child' => 'pembelian.tambahbarangbaru'],
            [':parent' => 'transaksiPembelian', ':child' => 'pembelian.total'],
            [':parent' => 'transaksiPembelian', ':child' => 'pembelian.ubah'],
            [':parent' => 'transaksiPembelian', ':child' => 'pembelian.updateqty'],
            [':parent' => 'transaksiPembelian', ':child' => 'pembelian.view'],
            [':parent' => 'transaksiPenjualan', ':child' => 'penjualan.ambilprofil'],
            [':parent' => 'transaksiPenjualan', ':child' => 'penjualan.exportcsv'],
            [':parent' => 'transaksiPenjualan', ':child' => 'penjualan.hapus'],
            [':parent' => 'transaksiPenjualan', ':child' => 'penjualan.hapusdetail'],
            [':parent' => 'transaksiPenjualan', ':child' => 'penjualan.import'],
            [':parent' => 'transaksiPenjualan', ':child' => 'penjualan.index'],
            [':parent' => 'transaksiPenjualan', ':child' => 'penjualan.printinvoice'],
            [':parent' => 'transaksiPenjualan', ':child' => 'penjualan.printnota'],
            [':parent' => 'transaksiPenjualan', ':child' => 'penjualan.printstruk'],
            [':parent' => 'transaksiPenjualan', ':child' => 'penjualan.simpanpenjualan'],
            [':parent' => 'transaksiPenjualan', ':child' => 'penjualan.tambah'],
            [':parent' => 'transaksiPenjualan', ':child' => 'penjualan.tambahdetail'],
            [':parent' => 'transaksiPenjualan', ':child' => 'penjualan.total'],
            [':parent' => 'transaksiPenjualan', ':child' => 'penjualan.ubah'],
            [':parent' => 'transaksiPenjualan', ':child' => 'penjualan.view'],
            [':parent' => 'transaksiReturPembelian', ':child' => 'returpembelian.ambilprofil'],
            [':parent' => 'transaksiReturPembelian', ':child' => 'returpembelian.caribarang'],
            [':parent' => 'transaksiReturPembelian', ':child' => 'returpembelian.getbaranginfo'],
            [':parent' => 'transaksiReturPembelian', ':child' => 'returpembelian.hapus'],
            [':parent' => 'transaksiReturPembelian', ':child' => 'returpembelian.hapusdetail'],
            [':parent' => 'transaksiReturPembelian', ':child' => 'returpembelian.index'],
            [':parent' => 'transaksiReturPembelian', ':child' => 'returpembelian.pilihinv'],
            [':parent' => 'transaksiReturPembelian', ':child' => 'returpembelian.printreturpembelian'],
            [':parent' => 'transaksiReturPembelian', ':child' => 'returpembelian.simpan'],
            [':parent' => 'transaksiReturPembelian', ':child' => 'returpembelian.tambah'],
            [':parent' => 'transaksiReturPembelian', ':child' => 'returpembelian.total'],
            [':parent' => 'transaksiReturPembelian', ':child' => 'returpembelian.ubah'],
            [':parent' => 'transaksiReturPembelian', ':child' => 'returpembelian.updateqty'],
            [':parent' => 'transaksiReturPembelian', ':child' => 'returpembelian.view'],
            [':parent' => 'transaksiReturPenjualan', ':child' => 'returpenjualan.ambilprofil'],
            [':parent' => 'transaksiReturPenjualan', ':child' => 'returpenjualan.hapus'],
            [':parent' => 'transaksiReturPenjualan', ':child' => 'returpenjualan.hapusdetail'],
            [':parent' => 'transaksiReturPenjualan', ':child' => 'returpenjualan.index'],
            [':parent' => 'transaksiReturPenjualan', ':child' => 'returpenjualan.simpan'],
            [':parent' => 'transaksiReturPenjualan', ':child' => 'returpenjualan.tambah'],
            [':parent' => 'transaksiReturPenjualan', ':child' => 'returpenjualan.tambahdetail'],
            [':parent' => 'transaksiReturPenjualan', ':child' => 'returpenjualan.total'],
            [':parent' => 'transaksiReturPenjualan', ':child' => 'returpenjualan.ubah'],
            [':parent' => 'transaksiReturPenjualan', ':child' => 'returpenjualan.view'],
            [':parent' => 'transaksiSO', ':child' => 'stockopname.gantirak'],
            [':parent' => 'transaksiSO', ':child' => 'stockopname.hapus'],
            [':parent' => 'transaksiSO', ':child' => 'stockopname.hapusdetail'],
            [':parent' => 'transaksiSO', ':child' => 'stockopname.index'],
            [':parent' => 'transaksiSO', ':child' => 'stockopname.inputqtymanual'],
            [':parent' => 'transaksiSO', ':child' => 'stockopname.scanbarcode'],
            [':parent' => 'transaksiSO', ':child' => 'stockopname.setinaktif'],
            [':parent' => 'transaksiSO', ':child' => 'stockopname.setnol'],
            [':parent' => 'transaksiSO', ':child' => 'stockopname.simpanso'],
            [':parent' => 'transaksiSO', ':child' => 'stockopname.tambah'],
            [':parent' => 'transaksiSO', ':child' => 'stockopname.tambahdetail'],
            [':parent' => 'transaksiSO', ':child' => 'stockopname.ubah'],
            [':parent' => 'transaksiSO', ':child' => 'stockopname.view'],
            [':parent' => 'DATA_ENTRY', ':child' => 'cekHarga'],
            [':parent' => 'DATA_ENTRY', ':child' => 'cetakFormSO'],
            [':parent' => 'DATA_ENTRY', ':child' => 'configBarang'],
            [':parent' => 'DATA_ENTRY', ':child' => 'configKategoriBarang'],
            [':parent' => 'DATA_ENTRY', ':child' => 'configProfil'],
            [':parent' => 'DATA_ENTRY', ':child' => 'configRakBarang'],
            [':parent' => 'DATA_ENTRY', ':child' => 'configSatuanBarang'],
            [':parent' => 'DATA_ENTRY', ':child' => 'transaksiHutangPiutang'],
            [':parent' => 'DATA_ENTRY', ':child' => 'transaksiPembelian'],
            [':parent' => 'DATA_ENTRY', ':child' => 'transaksiPenjualan'],
            [':parent' => 'DATA_ENTRY', ':child' => 'transaksiReturPembelian'],
            [':parent' => 'DATA_ENTRY', ':child' => 'transaksiReturPenjualan'],
            [':parent' => 'DATA_ENTRY', ':child' => 'transaksiSO'],
        ];
        foreach ($params as $param) {
            $this->execute($sql, $param);
        }
    }

    public function safeDown()
    {

    }

}
